# Generated by Django 5.1.1 on 2024-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=10)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
